"""A conversation with Gemma, where every turn also gets a trust report.

WHAT THIS IS FOR
`trust_report.py` reads one activation out of a stored corpus. That is the right
shape for the experiment and the wrong shape for someone who just wants to poke
at the NLA. This wraps the same machinery in a conversation: you talk to Gemma,
and after each turn you are shown what the NLA says the model was representing --
and which parts of that the SAE can actually corroborate.

WHERE THE ACTIVATION IS TAKEN
At the LAST TOKEN OF THE PROMPT -- the final token of the conversation as it
stands just before Gemma starts generating its reply. So the report answers:
*what was the model representing when it had finished reading you?*

Two consequences worth stating plainly:

  * On turn 3 the activation encodes turns 1 and 2 as well, because the whole
    conversation is re-fed each time. That is a real property of the measurement,
    not a shortcut: the state at that token genuinely carries the history.
  * This differs from the corpus, which samples random positions INSIDE Gemma's
    generated response. Same last-token-of-context structure -- every corpus row
    is also "the activation at the end of this text" -- but a different region.
    The corpus never places the position at a turn boundary.

WHY NOT ARBITRARY PASTED TEXT
The Gemma Scope 2 IT SAEs are fine-tuned on chat data whose assistant turns were
*generated by Gemma itself* (their paper: "we take open-source datasets of user
prompts and generate responses from the corresponding Gemma models"). Text from
anywhere else is off that distribution, and on FineWeb this same pipeline
measured a 7-point effect where Gemma rollouts gave 25. Having Gemma write the
conversation is what keeps the input in the distribution the SAE was fitted to.

The user still chooses the subject -- they just do it by prompting rather than
by pasting.

NO TRUNCATION IS NEEDED
The activation at position p already encodes every token before it, so a long
conversation loses nothing; it simply runs until the context window is full. The
2000-character cap in the corpus builder is a *display* limit on the saved text,
not a limit on the vector.

MODEL RESIDENCY
Three 12B models are involved. On a card that fits them all they stay resident
and a turn is fast. On a smaller card set `--phase` and each is loaded and
released per turn, which works but costs a minute or two of loading per reply.
"""

from __future__ import annotations

import gc
import sys
from dataclasses import dataclass, field
from pathlib import Path

import torch

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent / "src"))

import trust_report as TR                                          # noqa: E402
import judge_explanations as JE                                    # noqa: E402

#: Which matcher prompt the tool judges with. Must be a key of JE.PROMPTS --
#: asserted at import so a rename in the experiment breaks loudly here instead
#: of at the first turn a user takes.
JUDGE_PROMPT = "A"
assert JUDGE_PROMPT in JE.PROMPTS, (
    f"JUDGE_PROMPT={JUDGE_PROMPT!r} is not one of {sorted(JE.PROMPTS)}")
from hf_paths import sae_variant_dir, L0_SMALL                     # noqa: E402

# FVE = 1 - mean(MSE)/rawvar, and `rawvar` is a property of the ACTIVATION
# DISTRIBUTION, not of any one example -- a single conversation turn cannot
# produce it. This is the value measured over the 50-activation corpus, borrowed
# so all four comparisons can be shown. The page says it is borrowed.
CORPUS_RAWVAR = 0.02790951170027256


@dataclass
class Turn:
    """One exchange, plus what the SAE and the NLA each said about it."""
    user: str
    reply: str = ""
    explanation: str = ""          # what the AV said the activation contained
    confirmed: list = field(default_factory=list)
    unverified: list = field(default_factory=list)
    omitted: list = field(default_factory=list)
    n_confirmed: int = 0           # totals INCLUDE latents with no validated
    n_unverified: int = 0          # label; the lists above name only the ones
    n_omitted: int = 0             # that have one. ~half do.
    # The AR's own cosine for comparison B. Read cosine over FVE when comparing
    # turns: Gemma's tiny rawvar makes FVE magnify a cosine difference ~72x, so
    # FVE swings hard on differences that are barely there.
    cos: float | None = None
    position: int | None = None    # token index the activation came from
    n_context: int | None = None   # conversation length in tokens at that point
    cjk: bool = False              # injection-failure smell
    failed: str = ""               # set when the AV emitted no usable explanation
    fve: dict = field(default_factory=dict)      # all four comparisons, A-D
    covered: list = field(default_factory=list)  # latents the explanation states
    uncovered: list = field(default_factory=list)


class Session:
    """Holds the models and the conversation, and produces a Turn per exchange."""

    def __init__(self, av_path: str, ar_path: str, labels_path: str,
                 base: str = "google/gemma-3-12b-it", layer: int = 32,
                 device: str = "cuda", phase: bool = False,
                 max_new_tokens: int = 400, seed: int = 0):
        self.av_path, self.ar_path = av_path, ar_path
        self.base, self.layer, self.device = base, layer, device
        self.phase, self.max_new_tokens, self.seed = phase, max_new_tokens, seed
        self.history: list[dict] = []
        self.turns: list[Turn] = []

        self.labels = TR.json.loads(Path(labels_path).read_text())
        self.sae = TR.load_file(str(sae_variant_dir(L0_SMALL) / "params.safetensors"))

        # Held only when not phasing. `phase=True` trades speed for fitting on a
        # card that cannot hold three 12B models at once.
        self._base = self._tok = self._av = self._ar = None
        if not phase:
            # Load all three up front so the first turn is not slower than the
            # rest. Each loader is idempotent, so this is just a warm-up.
            self._load_base()
            self._load_av()
            self._load_ar()

    # ---------------------------------------------------------------- models

    def _load_base(self):
        """Load Gemma and unwrap it to the text-side CausalLM.

        resolve_text_model takes an ALREADY-LOADED model and unwraps it; it is
        not a loader and takes no dtype. This called it as though it were both,
        and unpacked two values from it, so the tool raised TypeError on the
        first turn. It is the same load-then-unwrap pattern
        extract_activations.py uses.

        The unwrap matters rather than being ceremony: Gemma-3 arrives as
        Gemma3ForConditionalGeneration, and reading hidden states off the
        wrapper instead of the text model is how you get activations from the
        wrong place.
        """
        if self._base is None:
            from transformers import AutoModelForCausalLM, AutoTokenizer
            from nla.arch_adapters import resolve_text_model
            self._tok = AutoTokenizer.from_pretrained(self.base)
            m = AutoModelForCausalLM.from_pretrained(self.base, dtype=torch.bfloat16)
            self._base = resolve_text_model(m).to(self.device).eval()
        return self._base, self._tok

    def _load_av(self):
        if self._av is None:
            self._av = TR.AVRunner(self.av_path, device=self.device)
        return self._av

    def _load_ar(self):
        if self._ar is None:
            self._ar = TR.NLACritic(self.ar_path, device=self.device)
        return self._ar

    def _sae_decode(self, acts):
        """b_dec is added on DECODE only -- subtracting it from the input before
        encoding was measured at cos 0.31 against the correct 0.99."""
        return acts @ self.sae["w_dec"] + self.sae["b_dec"]

    def _judge_covered(self, expl: str, latents: list[dict]) -> tuple[list, list]:
        """For each named latent, does the explanation actually state it?

        This is the ONLY part of a turn that involves a model judging anything --
        the buckets above are set arithmetic. It reuses the prompt the experiment
        uses, by name, from judge_explanations.PROMPTS.

        JUDGE_PROMPT is pinned to a name rather than reaching for a module
        private. The tool previously used `JE._PROMPT`, which was renamed when
        candidate prompts were added, and nothing caught it because the tool has
        never been executed -- it would have raised AttributeError on the first
        turn that judged anything.

        The prompt in use is A: the graded, strict wording, minus a claim that
        the explanation is "one or two sentences" which held for 3% of real
        explanations. Measured false-positive rate 4.6%, against 78.3% for the
        plain Yes/No wording it replaced.

        The experiment runs seven judgements per latent (1 matched + 3 unrelated
        explanations + 3 non-firing latents) to MEASURE that false-positive rate.
        Here only the matched judgement is run -- the rate is already known, and
        re-establishing it per turn would cost 7x for nothing.

        The judge is `gemma-3-12b-it`, the same model as the base, so no
        additional weights are loaded.
        """
        if not latents:
            return [], []
        model, tok = self._load_base()
        opt_ids = [tok.encode(o, add_special_tokens=False)[0] for o in JE.OPTS]
        prompts = [JE.PROMPTS[JUDGE_PROMPT].format(expl=expl, content=l["label"])
                   for l in latents]
        scores = JE.judge(model, tok, prompts, opt_ids, bs=12, log_every=10**9)
        covered, uncovered = [], []
        for l, s in zip(latents, scores):
            grade = JE.OPTS[int(max(range(len(s)), key=lambda i: s[i]))]
            row = dict(l, grade=grade)
            # CLEARLY and PROBABLY are "covered"; the experiment collapses them
            # the same way. NO sits BELOW the 25% base rate on known-absent
            # latents, so a "no" here is real evidence, not a shrug.
            (covered if grade in ("CLEARLY", "PROBABLY") else uncovered).append(row)
        return covered, uncovered

    def _release(self, *names):
        if not self.phase:
            return
        for n in names:
            setattr(self, n, None)
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # ---------------------------------------------------------------- a turn

    def ask(self, user_text: str) -> Turn:
        """Add a user message, capture the activation, generate, and report."""
        t = Turn(user=user_text)
        self.history.append({"role": "user", "content": user_text})

        # --- the activation, at the last token of the conversation so far ----
        base, tok = self._load_base()
        prompt = tok.apply_chat_template(self.history, tokenize=False,
                                          add_generation_prompt=True)
        ids = tok(prompt, return_tensors="pt",
                  add_special_tokens=False).input_ids.to(self.device)
        with torch.no_grad():
            hs = base(ids, output_hidden_states=True).hidden_states
        # --layer L == hidden_states[L+1]; index 0 is the embedding output.
        v = hs[self.layer + 1][0, -1].float().cpu()
        t.position = int(ids.shape[1]) - 1
        t.n_context = int(ids.shape[1])

        # --- Gemma's reply, sampled the same way the corpus was built --------
        torch.manual_seed(self.seed + len(self.turns))
        with torch.no_grad():
            g = base.generate(input_ids=ids, max_new_tokens=self.max_new_tokens,
                              do_sample=True, temperature=1.0,
                              pad_token_id=tok.pad_token_id or tok.eos_token_id)
        t.reply = tok.decode(g[0, ids.shape[1]:], skip_special_tokens=True).strip()
        self.history.append({"role": "assistant", "content": t.reply})
        self._release("_base", "_tok")

        # --- what the NLA says that activation contained ---------------------
        V = v.unsqueeze(0)
        av = self._load_av()
        torch.manual_seed(self.seed * 1000 + len(self.turns))
        # Returns None when the AV emits no well-formed <explanation> tag pair.
        # There is nothing to reconstruct from in that case, so the turn keeps
        # its reply and reports no latents rather than crashing.
        expl = av.generate(V[0], temperature=1.0,
                           explanation_max_tokens=200, do_sample=True)
        self._release("_av")
        if not expl:
            t.explanation = ""
            t.failed = "the AV produced no well-formed explanation for this turn"
            self.turns.append(t)
            return t
        t.explanation = expl
        # If injection silently fails the AV describes the marker character and
        # free-associates in CJK. This is the loudest smoke test for the whole
        # injection path, so it is surfaced rather than swallowed.
        t.cjk = bool(TR._CJK.search(expl))

        ar = self._load_ar()
        v_ar = ar.reconstruct(expl).float().cpu()
        mse_B, cos = ar.score(expl, v)
        t.cos = float(cos)
        self._release("_ar")

        # --- set arithmetic on the two latent sets ---------------------------
        # No model judgement anywhere in this part: the buckets are exactly
        # F_orig & F_ar, F_ar - F_orig, F_orig - F_ar.
        A_orig = TR.sae_encode(V, self.sae)
        A_ar = TR.sae_encode(v_ar.unsqueeze(0), self.sae)
        F_orig = set(A_orig[0].nonzero().flatten().tolist())
        F_ar = set(A_ar[0].nonzero().flatten().tolist())
        conf, unver, omit = F_orig & F_ar, F_ar - F_orig, F_orig - F_ar
        t.n_confirmed, t.n_unverified, t.n_omitted = len(conf), len(unver), len(omit)

        # --- the four reconstruction comparisons -----------------------------
        #   A  the SAE rebuilding the original activation
        #   B  the NLA round trip: activation -> text -> activation
        #   C  the SAE rebuilding the AR's output
        #   D  both lossy steps chained
        # mse is 2(1-cos) after normalisation, matching the AR's own scorer.
        V_sae = self._sae_decode(A_orig)
        V_ar_sae = self._sae_decode(A_ar)
        m = lambda a, b: float(2.0 * (1.0 - torch.nn.functional.cosine_similarity(
            a.flatten(), b.flatten(), dim=0)))
        for k, mse in (("A_sae_orig_vs_orig", m(V_sae, V)),
                       ("B_ar_vs_orig", float(mse_B)),
                       ("C_sae_ar_vs_ar", m(V_ar_sae, v_ar)),
                       ("D_sae_ar_vs_orig", m(V_ar_sae, V))):
            t.fve[k] = {"fve": 1.0 - mse / CORPUS_RAWVAR,
                        "cos": 1.0 - mse / 2.0}

        def named(fs):
            out = []
            for f in sorted(fs):
                e = self.labels.get(str(f))
                if e and e.get("reliable") and e.get("label"):
                    out.append({"id": int(f), "label": e["label"]})
            return out

        t.confirmed, t.unverified, t.omitted = named(conf), named(unver), named(omit)

        # --- does the explanation actually STATE these? ----------------------
        # Judged over every latent genuinely in the activation -- shared + lost.
        # `made` is excluded: those are not in the original, so asking whether
        # the text covers them answers a different question.
        t.covered, t.uncovered = self._judge_covered(
            expl, t.confirmed + t.omitted)
        self._release("_base", "_tok")

        self.turns.append(t)
        return t
