"""A conversation with Gemma, where every turn also gets a trust report.

WHAT THIS IS FOR
`trust_report.py` reads one activation out of a stored corpus. That is the right
shape for the experiment and the wrong shape for someone who just wants to poke
at the NLA. This wraps the same machinery in a conversation: you talk to Gemma,
and after each turn you are shown what the NLA says the model was representing --
and which parts of that the SAE can actually corroborate.

WHERE THE ACTIVATION IS TAKEN
At the LAST TOKEN OF THE PROMPT -- the final token of the conversation as it
stands just before Gemma starts generating its reply. So the report answers:
*what was the model representing when it had finished reading you?*

Two consequences worth stating plainly:

  * On turn 3 the activation encodes turns 1 and 2 as well, because the whole
    conversation is re-fed each time. That is a real property of the measurement,
    not a shortcut: the state at that token genuinely carries the history.
  * This differs from the corpus, which samples random positions INSIDE Gemma's
    generated response. Same last-token-of-context structure -- every corpus row
    is also "the activation at the end of this text" -- but a different region.
    The corpus never places the position at a turn boundary.

WHY NOT ARBITRARY PASTED TEXT
The Gemma Scope 2 IT SAEs are fine-tuned on chat data whose assistant turns were
*generated by Gemma itself* (their paper: "we take open-source datasets of user
prompts and generate responses from the corresponding Gemma models"). Text from
anywhere else is off that distribution, and on FineWeb this same pipeline
measured a 7-point effect where Gemma rollouts gave 25. Having Gemma write the
conversation is what keeps the input in the distribution the SAE was fitted to.

The user still chooses the subject -- they just do it by prompting rather than
by pasting.

NO TRUNCATION IS NEEDED
The activation at position p already encodes every token before it, so a long
conversation loses nothing; it simply runs until the context window is full. The
2000-character cap in the corpus builder is a *display* limit on the saved text,
not a limit on the vector.

MODEL RESIDENCY
Three 12B models are involved. On a card that fits them all they stay resident
and a turn is fast. On a smaller card set `--phase` and each is loaded and
released per turn, which works but costs a minute or two of loading per reply.
"""

from __future__ import annotations

import gc
import sys
from dataclasses import dataclass, field
from pathlib import Path

import torch

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent / "src"))

import trust_report as TR                                          # noqa: E402
from hf_paths import sae_variant_dir, L0_SMALL                     # noqa: E402


@dataclass
class Turn:
    """One exchange, plus what the SAE and the NLA each said about it."""
    user: str
    reply: str = ""
    explanation: str = ""          # what the AV said the activation contained
    confirmed: list = field(default_factory=list)
    unverified: list = field(default_factory=list)
    omitted: list = field(default_factory=list)
    n_confirmed: int = 0           # totals INCLUDE latents with no validated
    n_unverified: int = 0          # label; the lists above name only the ones
    n_omitted: int = 0             # that have one. ~half do.
    # cos only, no FVE: FVE needs `rawvar` over a corpus of activations, and a
    # single conversation turn has no corpus to compute it against. Cosine is
    # also the stable quantity here -- Gemma's tiny rawvar makes FVE magnify it
    # ~72x, so a per-turn FVE would swing wildly for no added information.
    cos: float | None = None
    position: int | None = None    # token index the activation came from
    n_context: int | None = None   # conversation length in tokens at that point
    cjk: bool = False              # injection-failure smell
    failed: str = ""               # set when the AV emitted no usable explanation


class Session:
    """Holds the models and the conversation, and produces a Turn per exchange."""

    def __init__(self, av_path: str, ar_path: str, labels_path: str,
                 base: str = "google/gemma-3-12b-it", layer: int = 32,
                 device: str = "cuda", phase: bool = False,
                 max_new_tokens: int = 400, seed: int = 0):
        self.av_path, self.ar_path = av_path, ar_path
        self.base, self.layer, self.device = base, layer, device
        self.phase, self.max_new_tokens, self.seed = phase, max_new_tokens, seed
        self.history: list[dict] = []
        self.turns: list[Turn] = []

        self.labels = TR.json.loads(Path(labels_path).read_text())
        self.sae = TR.load_file(str(sae_variant_dir(L0_SMALL) / "params.safetensors"))

        # Held only when not phasing. `phase=True` trades speed for fitting on a
        # card that cannot hold three 12B models at once.
        self._base = self._tok = self._av = self._ar = None
        if not phase:
            # Load all three up front so the first turn is not slower than the
            # rest. Each loader is idempotent, so this is just a warm-up.
            self._load_base()
            self._load_av()
            self._load_ar()

    # ---------------------------------------------------------------- models

    def _load_base(self):
        if self._base is None:
            from transformers import AutoTokenizer
            from nla.arch_adapters import resolve_text_model
            self._tok = AutoTokenizer.from_pretrained(self.base)
            m, _ = resolve_text_model(self.base, dtype=torch.bfloat16)
            self._base = m.to(self.device).eval()
        return self._base, self._tok

    def _load_av(self):
        if self._av is None:
            self._av = TR.AVRunner(self.av_path, device=self.device)
        return self._av

    def _load_ar(self):
        if self._ar is None:
            self._ar = TR.NLACritic(self.ar_path, device=self.device)
        return self._ar

    def _release(self, *names):
        if not self.phase:
            return
        for n in names:
            setattr(self, n, None)
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # ---------------------------------------------------------------- a turn

    def ask(self, user_text: str) -> Turn:
        """Add a user message, capture the activation, generate, and report."""
        t = Turn(user=user_text)
        self.history.append({"role": "user", "content": user_text})

        # --- the activation, at the last token of the conversation so far ----
        base, tok = self._load_base()
        prompt = tok.apply_chat_template(self.history, tokenize=False,
                                          add_generation_prompt=True)
        ids = tok(prompt, return_tensors="pt",
                  add_special_tokens=False).input_ids.to(self.device)
        with torch.no_grad():
            hs = base(ids, output_hidden_states=True).hidden_states
        # --layer L == hidden_states[L+1]; index 0 is the embedding output.
        v = hs[self.layer + 1][0, -1].float().cpu()
        t.position = int(ids.shape[1]) - 1
        t.n_context = int(ids.shape[1])

        # --- Gemma's reply, sampled the same way the corpus was built --------
        torch.manual_seed(self.seed + len(self.turns))
        with torch.no_grad():
            g = base.generate(input_ids=ids, max_new_tokens=self.max_new_tokens,
                              do_sample=True, temperature=1.0,
                              pad_token_id=tok.pad_token_id or tok.eos_token_id)
        t.reply = tok.decode(g[0, ids.shape[1]:], skip_special_tokens=True).strip()
        self.history.append({"role": "assistant", "content": t.reply})
        self._release("_base", "_tok")

        # --- what the NLA says that activation contained ---------------------
        V = v.unsqueeze(0)
        av = self._load_av()
        torch.manual_seed(self.seed * 1000 + len(self.turns))
        # Returns None when the AV emits no well-formed <explanation> tag pair.
        # There is nothing to reconstruct from in that case, so the turn keeps
        # its reply and reports no latents rather than crashing.
        expl = av.generate(V[0], temperature=1.0,
                           explanation_max_tokens=200, do_sample=True)
        self._release("_av")
        if not expl:
            t.explanation = ""
            t.failed = "the AV produced no well-formed explanation for this turn"
            self.turns.append(t)
            return t
        t.explanation = expl
        # If injection silently fails the AV describes the marker character and
        # free-associates in CJK. This is the loudest smoke test for the whole
        # injection path, so it is surfaced rather than swallowed.
        t.cjk = bool(TR._CJK.search(expl))

        ar = self._load_ar()
        v_ar = ar.reconstruct(expl).float().cpu()
        _, cos = ar.score(expl, v)
        t.cos = float(cos)
        self._release("_ar")

        # --- set arithmetic on the two latent sets ---------------------------
        # No model judgement anywhere in this part: the buckets are exactly
        # F_orig & F_ar, F_ar - F_orig, F_orig - F_ar.
        F_orig = set(TR.sae_encode(V, self.sae)[0].nonzero().flatten().tolist())
        F_ar = set(TR.sae_encode(v_ar.unsqueeze(0), self.sae)[0]
                   .nonzero().flatten().tolist())
        conf, unver, omit = F_orig & F_ar, F_ar - F_orig, F_orig - F_ar
        t.n_confirmed, t.n_unverified, t.n_omitted = len(conf), len(unver), len(omit)

        def named(fs):
            out = []
            for f in sorted(fs):
                e = self.labels.get(str(f))
                if e and e.get("reliable") and e.get("label"):
                    out.append({"id": int(f), "label": e["label"]})
            return out

        t.confirmed, t.unverified, t.omitted = named(conf), named(unver), named(omit)
        self.turns.append(t)
        return t
