#!/usr/bin/env bash
# Full pipeline, corpus to results. ~2.5h on one 80GB GPU.
#
# Each stage is independently runnable; this script is the documented order.
# Every stage writes its outputs before the next begins, so a failure mid-way
# does not cost the stages already done.
set -euo pipefail

# ---- configuration -----------------------------------------------------------
: "${NLA_REPO:?set NLA_REPO to a clone of kitft/natural_language_autoencoders}"
AV="${AV:?set AV to the nla-gemma3-12b-L32-av snapshot directory}"
AR="${AR:?set AR to the nla-gemma3-12b-L32-ar snapshot directory}"
N_DOCS="${N_DOCS:-50}"
PARQUET="${PARQUET:-acts_rollout${N_DOCS}_L32.parquet}"
OUT="${OUT:-results}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$HERE/src"
export NLA_REPO
mkdir -p "$OUT"

# ---- 1. corpus ---------------------------------------------------------------
# oasst1 + LMSYS prompts with responses generated by Gemma itself -- the recipe
# the Gemma Scope 2 IT SAEs were fine-tuned on. Running on anything else costs a
# lot: on FineWeb the same pipeline measured a 7-point effect where these
# rollouts gave 25.
#
# Skipped if the parquet exists, because generation is the slow part and an
# earlier run lost 25 minutes to a crash in a later stage.
echo "=== 1/6  corpus + activations ==="
if [ -f "$PARQUET" ]; then
  echo "    $PARQUET exists, skipping (delete it to rebuild)"
else
  python "$SRC/extract_activations.py" --arm rollout \
      --n-docs "$N_DOCS" --positions-per-doc 10 --seed 42 --out "$PARQUET"
fi

# ---- 2. round trip -----------------------------------------------------------
# AV -> explanation -> AR -> reconstruction, then the SAE on both ends.
# Saves all four vector families and per-example FVE for all four comparisons.
echo "=== 2/6  round trip (AV -> AR) + SAE ==="
python "$SRC/roundtrip.py" --av "$AV" --ar "$AR" \
    --parquet "$PARQUET" --n "$N_DOCS" --runs 5 --out-dir "$OUT"

# ---- 3. re-encode under both sparsities --------------------------------------
# Seconds, no model. l0_big for the reconstruction claim (strongest SAE, so
# "the AR beats it" is the harder claim); l0_small for anything about feature
# MEANING, because l0_big's labels cannot be told from wrong ones.
echo "=== 3/6  re-encode under both SAEs ==="
for S in l0_small l0_big; do
  python "$SRC/refeature.py" --dirs "$OUT" --labels rollout \
      --sae "$S" --out-name "feature_overlap_$S.json"
done

# ---- 4. label the features ---------------------------------------------------
# Generates 3 candidates, picks the winner on one held-out band, REPORTS it on a
# second disjoint band, and keeps it only if it beats the 95th percentile of a
# wrong-label null. Caches by feature id, so re-running is cheap.
echo "=== 4/6  label features (validated auto-interp) ==="
python "$SRC/label_features.py" --dirs "$OUT" \
    --out "$OUT/feature_labels.json" --batch 6

# ---- 5. judge + describe -----------------------------------------------------
# judge_explanations: per feature, does the explanation cover it?
#   CLEARLY / PROBABLY / UNCLEAR / NO, against two nulls.
# describe_buckets: what do shared/lost/made say, from the labels ALONE --
#   the describer never sees the explanation, so agreement is evidence.
echo "=== 5/6  judge explanations + blind descriptions ==="
python "$SRC/judge_explanations.py" --dirs "$OUT" --names rollout \
    --labels-json "$OUT/feature_labels.json" --out "$OUT/grounding.json"
python "$SRC/describe_buckets.py" --dirs "$OUT" --names rollout \
    --labels-json "$OUT/feature_labels.json" --out "$OUT/bucket_descriptions.json"

# ---- 6. classify features ----------------------------------------------------
# grammar/content x generic/specific x is-it-actually-in-the-text, each against
# a control on a DIFFERENT document. Needs the source text, which stage 2 saves.
echo "=== 6/6  classify features against the source text ==="
python "$SRC/classify_features.py" --dir "$OUT" \
    --out "$OUT/feature_classification.json"

echo
echo "Done. Check these first, in this order:"
echo "  1. the FVE gate log in $OUT/feature_overlap.json -- it SELECTS activations"
echo "     on the outcome metric, and every seed tried is recorded"
echo "  2. validated label count in stage 4's output. ~50% is expected; much"
echo "     lower means the labeller is failing, not that the features are hard"
echo "  3. false-positive rate in $OUT/grounding.json. It should be under ~10%."
echo "     An earlier prompt scored 78% and made every downstream number void"
echo "  4. control columns everywhere. If a control is close to its matched"
echo "     number, that measurement is not discriminating and must not be quoted"
