"""A handful of single activations, written out end to end.

WHY THIS EXISTS
`results/LATENTS_BY_BUCKET.md` covers all 200 activations and is 950 KB. It is a
reference, not something anyone reads. These are six worked examples, chosen to
span the range, so a reader can follow one activation from the text Gemma wrote,
through what the SAE found in it, to what the AV said and what the judge made of
each latent -- without taking anything on trust.

NO GPU, NO MODEL. Everything comes from the committed artefacts, so anyone who
clones the repo can regenerate these and check them. The earlier version of this
directory was produced by a script that needed three 12B models resident, which
is why it went stale and ended up shipping a claim that had been withdrawn.

WHAT IS SHOWN PER ACTIVATION
  * the conversation, and where in it the activation was taken
  * the AV's explanation, split into the two segments the judging uses
  * FVE and Jaccard for all three variants
  * every validated latent, grouped shared / lost / made, with the judge's
    verdict under each variant

WHAT THE VERDICTS MEAN
  stated       the explanation was judged to convey this latent
  not stated   it was not
  undecidable  the judge also matched this latent to unrelated explanations, or
               matched this explanation to latents that never fired, so the
               measurement refused itself rather than guessing

Usage:
    python src/example_reports.py --dir results --n 6
"""

from __future__ import annotations

import argparse
import json
import statistics as st
from pathlib import Path

FLD = {"shared": "shared_features", "lost": "lost_features",
       "made": "invented_features"}
VARIANTS = ("full", "final_only", "no_final")
GLOSS = {"shared": "in the activation, and the rebuild recovered it",
         "lost": "in the activation, and the rebuild lost it",
         "made": "NOT in the activation — the rebuild produced it"}


def pick(acts: list[int], fve: dict, n: int) -> list[int]:
    """Span the FVE range rather than taking the first n.

    Six consecutive activations would all be ordinary. Sampling across the
    distribution means the set includes a case the round trip handled badly,
    which is the more informative one to be able to read.
    """
    ranked = sorted(acts, key=lambda a: fve[a])
    if n >= len(ranked):
        return ranked
    idx = [round(i * (len(ranked) - 1) / (n - 1)) for i in range(n)]
    return [ranked[i] for i in sorted(set(idx))]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dir", default="results")
    ap.add_argument("--n", type=int, default=6)
    ap.add_argument("--out", default=None, help="defaults to <dir>/example_reports")
    a = ap.parse_args()
    d = Path(a.dir)
    out = Path(a.out) if a.out else d / "example_reports"
    out.mkdir(parents=True, exist_ok=True)
    for old in out.glob("*.md"):
        old.unlink()

    ov = json.loads((d / "feature_overlap.json").read_text())
    sm = json.loads((d / "feature_overlap_l0_small.json").read_text())
    lab = json.loads((d / "feature_labels.json").read_text())
    gr = json.loads((d / "grounding.json").read_text())

    val = {int(k): v for k, v in lab.items()
           if isinstance(v, dict) and v.get("reliable") and v.get("label")}
    # verdicts keyed by (activation, latent, variant)
    V = {(r["act"], r["feature"], r["variant"]): r for r in gr["rows"]}
    run = {(r["act"], r["variant"]): r for r in ov["runs"]}
    bkt = {(r["act"], r["variant"]): {b: set(r[k]) for b, k in FLD.items()}
           for r in sm["runs"]}
    jac = {(r["act"], r["variant"]): r["jaccard"] for r in sm["runs"]}

    acts = sorted({r["act"] for r in ov["runs"] if r["variant"] == "full"})
    fve = {a: run[(a, "full")]["fve_B"] for a in acts}
    chosen = pick(acts, fve, a.n)

    index = ["# Worked examples", "",
             "Six single activations, followed end to end. Chosen to span the "
             "reconstruction range rather than taken in order, so the set "
             "includes cases the round trip handled badly.", "",
             "Generated by `src/example_reports.py` from the committed "
             "artefacts — no model is run, so these can be regenerated and "
             "checked by anyone with the repo.", "",
             "| | activation | FVE | shared / lost / made | conversation |",
             "|---|---|---:|---|---|"]

    for n, act in enumerate(chosen):
        r = run[(act, "full")]
        b = bkt[(act, "full")]
        L = [f"# Activation {act}", "",
             f"Reconstruction FVE **{r['fve_B']:+.3f}**, cosine "
             f"`{r['cos']:.4f}`. Jaccard against its own rebuild "
             f"**{jac[(act,'full')]:.3f}**, against an unrelated activation "
             f"*{r['control_jaccard']:.4f}*.", ""]

        if r.get("prompt"):
            L += ["## What Gemma was asked", "",
                  "> " + " ".join(r["prompt"].split())[:600], ""]
        if r.get("response"):
            pos = r.get("activation_token_index")
            off = r.get("offset_into_response")
            where = (f" The activation is token {pos}"
                     + (f", {off} tokens into the response." if off else ".")
                     ) if pos else ""
            L += ["## What Gemma wrote", "",
                  f"<details><summary>full response</summary>{where}", "",
                  "> " + " ".join(r["response"].split())[:2500], "",
                  "</details>", ""]

        # the explanation, and the two segments the judging actually uses
        L += ["## What the AV said about the activation", ""]
        paras = [p.strip() for p in (r["explanation"] or "").split("\n\n") if p.strip()]
        i = next((k for k, p in enumerate(paras) if "final token" in p.lower()),
                 len(paras) - 1)
        L += ["**Segment 1** — `no_final`, everything before the final-token "
              "paragraph:", ""]
        for p in paras[:i]:
            L.append("> " + " ".join(p.split()))
            L.append(">")
        L += ["", "**Segment 2** — `final_only`, the final-token paragraph:", ""]
        for p in paras[i:]:
            L.append("> " + " ".join(p.split()))
            L.append(">")
        L += ["", "The judge sees these two separately; `full` is scored as "
              "whichever latents *either* segment conveys.", ""]

        L += ["## What each cut reconstructs", "",
              "| variant | FVE | Jaccard | shared | lost | made |",
              "|---|---:|---:|---:|---:|---:|"]
        for v in VARIANTS:
            if (act, v) not in run:
                continue
            bb = bkt[(act, v)]
            L.append(f"| `{v}` | {run[(act,v)]['fve_B']:+.3f} | "
                     f"{jac[(act,v)]:.3f} | {len(bb['shared'])} | "
                     f"{len(bb['lost'])} | {len(bb['made'])} |")
        L.append("")

        L += ["## Every validated latent, and what the judge said", "",
              "`shared` + `lost` is F_orig — the latents genuinely in this "
              "activation. `made` was never in it.", ""]
        for bucket in ("shared", "lost", "made"):
            fs = sorted(b[bucket])
            named = [f for f in fs if f in val]
            L += [f"### {bucket.upper()} — {GLOSS[bucket]}", "",
                  f"*{len(named)} of {len(fs)} carry a validated label and can "
                  f"be shown.*", ""]
            if not named:
                L += ["*(none labelled)*", ""]
                continue
            L += ["| latent | what it responds to | full | final_only | no_final |",
                  "|---|---|---|---|---|"]
            for f in named:
                cells = []
                for v in VARIANTS:
                    rec = V.get((act, f, v))
                    cells.append({"present": "**stated**",
                                  "not_present": "not stated",
                                  "unknown": "*undecidable*"}.get(
                                      (rec or {}).get("verdict"), "—"))
                lbl = val[f]["label"].replace("|", "\\|")[:90]
                L.append(f"| `f{f}` | {lbl} | " + " | ".join(cells) + " |")
            L.append("")

        name = f"activation_{act:03d}.md"
        (out / name).write_text("\n".join(L) + "\n")
        conv = " ".join((r.get("prompt") or "")[:60].split())
        index.append(f"| {n+1} | [{act}]({name}) | {r['fve_B']:+.3f} | "
                     f"{len(b['shared'])} / {len(b['lost'])} / {len(b['made'])} "
                     f"| {conv}… |")

    index += ["", "Column meanings and the verdict vocabulary are in each "
                  "report. `RESULTS.md` has the aggregate numbers; these are "
                  "here so the aggregates can be spot-checked against "
                  "individual cases."]
    (out / "README.md").write_text("\n".join(index) + "\n")
    print(f"wrote {len(chosen)} reports + README to {out}")
    for act in chosen:
        print(f"  activation {act:>3}  FVE {fve[act]:+.3f}")


if __name__ == "__main__":
    main()
