"""Extract Gemma-3-12B-IT activations from CHAT data, two ways.

WHY THIS EXISTS
The FineWeb run found the SAE reconstructs worse than the AR (cos 0.9917 vs
0.9959). But that comparison is confounded: per the Gemma Scope 2 technical
paper the IT SAEs were fine-tuned on chat data, while the NLA was trained on
50/50 WildChat + Ultra-FineWeb. FineWeb is out-of-distribution for the SAE and
half in-distribution for the NLA, so the result may be about corpora, not
representations. This produces the two chat corpora that test that.

  arm "rollout"  — the SAE's EXACT documented recipe:
      "we take open-source datasets of user prompts and generate responses from
       the corresponding Gemma models" — prompts from OpenAssistant/oasst1 and
       LMSYS-Chat-1M, responses generated by Gemma-3-12B-IT ITSELF.
  arm "wildchat"  — real user<->ChatGPT conversations used AS-IS, chat-templated
      for Gemma. Gemma reads text it did not write.

NOTE ON THE NLA SIDE: how the NLA's WildChat half was processed is NOT publicly
determinable — neither this fork nor upstream kitft/natural_language_autoencoders
contains the conversation extractor (`grep wildchat` finds only a comment in
model_presets.py and a rollout-inspection script; extractors.py has only the
raw-text HFExtractor). So "wildchat as-is" is an informed guess at their recipe,
whereas "rollout" is quoted from the Gemma Scope 2 paper. Weight conclusions
accordingly.

WHY NOT stage0_extract: it has only a raw-text path. Feeding conversation text
through it samples positions anywhere — including mid-prompt and inside chat
control tokens — so the activations would not be from where either the SAE or
the NLA saw them. This applies the chat template, locates the ASSISTANT RESPONSE
region (what model_presets.py calls "where the interesting tokens start"), and
samples only inside it, with special tokens masked as the paper specifies.

Output schema matches stage0 exactly, so downstream scripts need no changes.

Usage:
    python src/extract_activations.py --arm rollout \
        --n-docs 10 --positions-per-doc 10 --out acts_gemma_rollout_L32.parquet
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq
import torch
import yaml
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
# nla/ comes from the upstream repo (kitft/natural_language_autoencoders); point
# NLA_REPO at a clone, or place this repo inside one. arch_adapters is what knows
# about Gemma-3's multimodal wrapper, its nested text_config, and the sqrt(d)
# embed scale -- calling AutoModelForCausalLM directly here would break.
_UP = os.environ.get("NLA_REPO") or str(_HERE.parent.parent)
sys.path.insert(0, _UP)
from nla.arch_adapters import resolve_text_model  # noqa: E402

BASE = "google/gemma-3-12b-it"
# Same floor stage0 uses: an activation needs enough left-context to mean
# anything. Applied WITHIN the response region here, not from sequence start.
_MIN_OFFSET = 16


def quality_prompts_oasst(n: int, seed: int) -> list[str]:
    """English root prompts that PASSED human review, non-deleted, non-synthetic.

    oasst1 ships 461k human quality ratings; using them is the difference
    between 'real quality data' and whatever happens to be first in the file.
    """
    ds = load_dataset("OpenAssistant/oasst1", split="train")
    ds = ds.filter(lambda r: (
        r["role"] == "prompter" and r["parent_id"] is None and r["lang"] == "en"
        and not r["deleted"] and not r.get("synthetic", False)
        and r.get("review_result") is True and (r.get("review_count") or 0) >= 2
        and 80 <= len(r["text"]) <= 1200
    ))
    idx = np.random.default_rng(seed).permutation(len(ds))[:n]
    return [ds[int(i)]["text"] for i in idx]


def quality_prompts_lmsys(n: int, seed: int) -> list[str]:
    """First user turn of English, non-redacted LMSYS conversations."""
    ds = load_dataset("lmsys/lmsys-chat-1m", split="train", streaming=True)
    out = []
    for r in ds:
        if len(out) >= n * 6:
            break
        if r.get("language") != "English" or r.get("redacted"):
            continue
        conv = r["conversation"]
        if conv and conv[0]["role"] == "user" and 80 <= len(conv[0]["content"]) <= 1200:
            out.append(conv[0]["content"])
    idx = np.random.default_rng(seed).permutation(len(out))[:n]
    return [out[int(i)] for i in idx]


def wildchat_conversations(n: int, seed: int) -> list[list[dict]]:
    """English, non-toxic, non-redacted WildChat conversations with a
    substantive assistant turn (so we do not extract from 'Sure!')."""
    ds = load_dataset("allenai/WildChat-1M", split="train", streaming=True)
    out = []
    for r in ds:
        if len(out) >= n * 8:
            break
        if r.get("language") != "English" or r.get("toxic") or r.get("redacted"):
            continue
        conv = r["conversation"]
        if len(conv) < 2 or conv[0]["role"] != "user" or conv[1]["role"] != "assistant":
            continue
        if len(conv[1]["content"]) < 400 or len(conv[0]["content"]) > 1200:
            continue
        out.append([{"role": c["role"], "content": c["content"]} for c in conv[:2]])
    idx = np.random.default_rng(seed).permutation(len(out))[:n]
    return [out[int(i)] for i in idx]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--arm", required=True, choices=["rollout", "wildchat"])
    ap.add_argument("--n-docs", type=int, default=10,
                    help="conversations to generate. ONE ACTIVATION EACH by "
                         "default, so this is also the number of independent "
                         "samples the experiment ends up with")
    ap.add_argument("--positions-per-doc", type=int, default=1,
                    help="activations taken from each conversation. LEAVE AT 1. "
                         "Two positions in one Gemma response share nearly all "
                         "their context -- an earlier run sampled 10 apiece and "
                         "two of them landed one token apart, which is not two "
                         "measurements of anything. Raising this inflates the "
                         "row count without adding independent samples, and "
                         "every downstream confidence interval silently narrows")
    ap.add_argument("--layer-index", type=int, default=32)
    ap.add_argument("--max-new-tokens", type=int, default=400, help="rollout arm only")
    ap.add_argument("--min-response-chars", type=int, default=400,
                    help="reject short Gemma responses. Without this, some prompts "
                         "elicit ~100-char replies, leaving too few response positions "
                         "to sample from -- the 10 sampled positions then come from one "
                         "short reply and are near-duplicates. Same bar the wildchat arm "
                         "applies to its assistant turns, so the two arms match.")
    ap.add_argument("--oversample", type=int, default=3,
                    help="generate this many times --n-docs prompts, since short "
                         "responses get rejected")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    sys.stdout.reconfigure(line_buffering=True)
    print("=" * 72); print(f"CHAT ACTIVATION EXTRACTION — arm={a.arm}"); print("=" * 72)

    tok = AutoTokenizer.from_pretrained(BASE)
    model = AutoModelForCausalLM.from_pretrained(BASE, dtype=torch.bfloat16).to(a.device)
    model = resolve_text_model(model); model.eval()

    # ---- build conversations ----
    if a.arm == "rollout":
        want = a.n_docs * a.oversample
        half = (want + 1) // 2
        prompts = quality_prompts_oasst(half, a.seed) + quality_prompts_lmsys(want - half, a.seed)
        print(f"[data] {len(prompts)} quality-filtered prompts "
              f"(oasst1 + LMSYS, as the Gemma Scope 2 paper specifies)")
        convs, srcs, rejected = [], [], 0
        for p in prompts:
            if len(convs) >= a.n_docs:
                break
            ids = tok.apply_chat_template([{"role": "user", "content": p}],
                                          tokenize=True, add_generation_prompt=True,
                                          return_tensors="pt").to(a.device)
            # SEEDED. Without this the rollout responses are unreproducible, and
            # when the parquet is lost the source text behind the results is gone
            # permanently -- which is exactly what happened to the first run.
            torch.manual_seed(a.seed * 100003 + len(convs))
            with torch.no_grad():
                g = model.generate(input_ids=ids, max_new_tokens=a.max_new_tokens,
                                   do_sample=True, temperature=1.0)
            resp = tok.decode(g[0][ids.shape[1]:], skip_special_tokens=True).strip()
            if len(resp) < a.min_response_chars:
                rejected += 1
                print(f"  [reject] prompt {len(p)}c -> response only {len(resp)}c")
                continue
            k = len(convs)
            convs.append([{"role": "user", "content": p},
                          {"role": "assistant", "content": resp}])
            srcs.append(f"rollout:oasst1+lmsys:{k}")
            print(f"  [{k}] prompt {len(p)}c -> Gemma response {len(resp)}c")
        print(f"[gen] kept {len(convs)}, rejected {rejected} for short responses")
        assert len(convs) >= a.n_docs, (
            f"only {len(convs)} usable of {a.n_docs} wanted -- raise --oversample")
    else:
        convs = wildchat_conversations(a.n_docs, a.seed)
        srcs = [f"wildchat:{k}" for k in range(len(convs))]
        print(f"[data] {len(convs)} quality-filtered WildChat conversations "
              f"(English, non-toxic, non-redacted, substantive assistant turn)")

    # ---- extract activations from inside the ASSISTANT RESPONSE ----
    special = set(tok.all_special_ids)          # paper masks pad/BOS/EOS
    rows, rng = [], np.random.default_rng(a.seed)
    for k, conv in enumerate(convs):
        full = tok.apply_chat_template(conv, tokenize=False)
        # prefix through the user turn + generation header; everything after is
        # the assistant response, which is the region both the SAE and the NLA
        # would have seen tokens from.
        prefix = tok.apply_chat_template([conv[0]], tokenize=False, add_generation_prompt=True)
        ids = tok(full, return_tensors="pt", add_special_tokens=False).input_ids.to(a.device)
        n_prefix = tok(prefix, return_tensors="pt", add_special_tokens=False).input_ids.shape[1]
        with torch.no_grad():
            hs = model(ids, output_hidden_states=True).hidden_states
        H = hs[a.layer_index + 1][0]            # --layer-index L == hidden_states[L+1]

        lo, hi = n_prefix + _MIN_OFFSET, ids.shape[1]
        cand = [p for p in range(lo, hi) if int(ids[0, p]) not in special]
        if len(cand) < a.positions_per_doc:
            print(f"  [skip] doc {k}: only {len(cand)} valid response positions")
            continue
        for p in rng.choice(cand, a.positions_per_doc, replace=False):
            rows.append({
                "n_raw_tokens": int(ids.shape[1]),
                # Context the activation actually encodes: everything up to and
                # including its token. Capped, because it is what gets shown.
                "detokenized_text_truncated": tok.decode(ids[0, :int(p) + 1],
                                                          skip_special_tokens=True)[-2000:],
                # THE WHOLE CONVERSATION, UNCUT. The line above stops at the
                # activation and keeps only its last 2000 characters, so on its
                # own it loses the prompt and everything Gemma wrote afterwards.
                # Storing the full text costs a few MB across the corpus and is
                # the difference between being able to re-examine a case later
                # and not. An earlier corpus was generated unseeded and then
                # lost, and its text was unrecoverable.
                "prompt": conv[0]["content"],
                "response": conv[1]["content"],
                "activation_token_index": int(p),
                "response_start_index": int(n_prefix),
                "activation_vector": H[int(p)].float().cpu().numpy().tolist(),
                "activation_layer": a.layer_index,
                "doc_id": srcs[k],
            })
        print(f"  doc {k}: {ids.shape[1]} tok, response starts at {n_prefix}, "
              f"{len(cand)} valid positions -> {a.positions_per_doc} sampled")

    t = pa.Table.from_pylist(rows)
    pq.write_table(t, a.out)
    Path(a.out + ".nla_meta.yaml").write_text(yaml.safe_dump({
        "kind": "nla_dataset", "schema_version": 1, "stage": "base",
        "row_count": len(rows),
        "dataset_id": f"chat_{a.arm}_gemma-3-12b-it_L{a.layer_index}",
        "extraction": {"base_model": BASE, "d_model": len(rows[0]["activation_vector"]),
                        "layer_index": a.layer_index, "norm": "none",
                        "corpus": ("oasst1+lmsys prompts, Gemma-generated responses"
                                    if a.arm == "rollout" else "allenai/WildChat-1M as-is"),
                        "positions_per_doc": a.positions_per_doc,
                        "sampled_region": "assistant response only, special tokens masked"},
    }, sort_keys=False))
    print(f"\nwrote {len(rows)} rows from {len(set(r['doc_id'] for r in rows))} docs -> {a.out}")


if __name__ == "__main__":
    main()
