"""Extract Gemma-3-12B-IT activations from CHAT data, three ways.

WHY THIS EXISTS
The FineWeb run found the SAE reconstructs worse than the AR (cos 0.9917 vs
0.9959). But that comparison is confounded: per the Gemma Scope 2 technical
paper the IT SAEs were fine-tuned on chat data, while the NLA was trained on
50/50 WildChat + Ultra-FineWeb. FineWeb is out-of-distribution for the SAE and
half in-distribution for the NLA, so the result may be about corpora, not
representations. This produces the two chat corpora that test that.

  arm "saecorpus" — THE DEFAULT. Gemma Scope's own corpus, sampled straight out
      of the `tokens` array in examples.safetensors: 236,783 finished Gemma chat
      conversations that this project already downloads and already reads for
      labelling. No generation, so stage 1 drops from hours to minutes, and the
      text is byte-identical on every re-run.
  arm "rollout"  — the SAE's documented recipe, reproduced by us:
      "we take open-source datasets of user prompts and generate responses from
       the corresponding Gemma models" — prompts from OpenAssistant/oasst1 and
       LMSYS-Chat-1M, responses generated by Gemma-3-12B-IT ITSELF. ~400 decode
       steps per conversation. Kept so the two corpora stay comparable.
  arm "wildchat"  — real user<->ChatGPT conversations used AS-IS, chat-templated
      for Gemma. Gemma reads text it did not write.

NOTE ON THE NLA SIDE: how the NLA's WildChat half was processed is NOT publicly
determinable — neither this fork nor upstream kitft/natural_language_autoencoders
contains the conversation extractor (`grep wildchat` finds only a comment in
model_presets.py and a rollout-inspection script; extractors.py has only the
raw-text HFExtractor). So "wildchat as-is" is an informed guess at their recipe,
whereas "rollout" is quoted from the Gemma Scope 2 paper. Weight conclusions
accordingly.

WHY NOT stage0_extract: it has only a raw-text path. Feeding conversation text
through it samples positions anywhere — including mid-prompt and inside chat
control tokens — so the activations would not be from where either the SAE or
the NLA saw them. This applies the chat template, locates the ASSISTANT RESPONSE
region (what model_presets.py calls "where the interesting tokens start"), and
samples only inside it, with special tokens masked as the paper specifies.

Output schema matches stage0 exactly, so downstream scripts need no changes.

Usage:
    python src/extract_activations.py --arm saecorpus \
        --n-docs 10 --positions-per-doc 10 --out acts_gemma_rollout_L32.parquet
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq
import torch
import yaml
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
# nla/ comes from the upstream repo (kitft/natural_language_autoencoders); point
# NLA_REPO at a clone, or place this repo inside one. arch_adapters is what knows
# about Gemma-3's multimodal wrapper, its nested text_config, and the sqrt(d)
# embed scale -- calling AutoModelForCausalLM directly here would break.
_UP = os.environ.get("NLA_REPO") or str(_HERE.parent.parent)
sys.path.insert(0, _UP)
from nla.arch_adapters import resolve_text_model  # noqa: E402

BASE = "google/gemma-3-12b-it"
# An activation needs enough left-context to mean anything; earlier positions
# decode to noise. Upstream stage0 uses _MIN_POSITION = 50 measured from the
# SEQUENCE start. This is measured from the RESPONSE start instead, because a
# position inside the user's prompt is not where either the SAE or the NLA saw
# tokens -- so the two numbers are not directly comparable and 16 here was NOT
# equivalent to 50 there.
#
# Measured on the SAE corpus, whose model turn begins at a median token 26:
#   offset 16 -> absolute floor ~42 from sequence start, BELOW the paper's 50
#   offset 50 -> absolute floor ~76, comfortably above it
# So 16 was quietly the looser setting. 50 costs almost nothing -- usable
# conversations go 123/128 -> 121/128, median valid positions 465 -> 431.
_MIN_OFFSET = 50

# Offsets for the near-miss control (roundtrip.py section "distance sweep").
# Signed and kept separate -- text before the activation is context it encodes,
# text after is context it cannot, so -20 and +20 are not the same measurement
# and must never be averaged together.
_NEIGHBOR_OFFSETS = (-50, -20, -5, 5, 20, 50)

# The corpus Gemma Scope ships alongside the SAE. Already downloaded by this
# project's setup step (the allow_patterns glob covers it) and already read by
# label_features.py, which decodes context snippets out of the same `tokens`
# array to build each latent's label.
_SAE_REPO = "google/gemma-scope-2-12b-it"
_SAE_EXAMPLES = "resid_post_all/layer_32_width_16k_l0_small/examples.safetensors"


def quality_prompts_oasst(n: int, seed: int) -> list[str]:
    """English root prompts that PASSED human review, non-deleted, non-synthetic.

    oasst1 ships 461k human quality ratings; using them is the difference
    between 'real quality data' and whatever happens to be first in the file.
    """
    ds = load_dataset("OpenAssistant/oasst1", split="train")
    ds = ds.filter(lambda r: (
        r["role"] == "prompter" and r["parent_id"] is None and r["lang"] == "en"
        and not r["deleted"] and not r.get("synthetic", False)
        and r.get("review_result") is True and (r.get("review_count") or 0) >= 2
        and 80 <= len(r["text"]) <= 1200
    ))
    idx = np.random.default_rng(seed).permutation(len(ds))[:n]
    return [ds[int(i)]["text"] for i in idx]


def quality_prompts_lmsys(n: int, seed: int) -> list[str]:
    """First user turn of English, non-redacted LMSYS conversations."""
    ds = load_dataset("lmsys/lmsys-chat-1m", split="train", streaming=True)
    out = []
    for r in ds:
        if len(out) >= n * 6:
            break
        if r.get("language") != "English" or r.get("redacted"):
            continue
        conv = r["conversation"]
        if conv and conv[0]["role"] == "user" and 80 <= len(conv[0]["content"]) <= 1200:
            out.append(conv[0]["content"])
    idx = np.random.default_rng(seed).permutation(len(out))[:n]
    return [out[int(i)] for i in idx]


def wildchat_conversations(n: int, seed: int) -> list[list[dict]]:
    """English, non-toxic, non-redacted WildChat conversations with a
    substantive assistant turn (so we do not extract from 'Sure!')."""
    ds = load_dataset("allenai/WildChat-1M", split="train", streaming=True)
    out = []
    for r in ds:
        if len(out) >= n * 8:
            break
        if r.get("language") != "English" or r.get("toxic") or r.get("redacted"):
            continue
        conv = r["conversation"]
        if len(conv) < 2 or conv[0]["role"] != "user" or conv[1]["role"] != "assistant":
            continue
        if len(conv[1]["content"]) < 400 or len(conv[0]["content"]) > 1200:
            continue
        out.append([{"role": c["role"], "content": c["content"]} for c in conv[:2]])
    idx = np.random.default_rng(seed).permutation(len(out))[:n]
    return [out[int(i)] for i in idx]


def saecorpus_docs(n: int, seed: int, tok,
                   min_response_tokens: int = _MIN_OFFSET + 16) -> list[dict]:
    """Sample N conversations from the corpus Gemma Scope ships with the SAE.

    WHY THIS EXISTS: the `rollout` arm reproduces Gemma Scope's recipe by
    generating responses ourselves -- ~400 sequential decode steps per
    conversation, which is ~3.3h at n=200 and the single most expensive stage in
    the pipeline. But `examples.safetensors` already contains 236,783 finished
    Gemma chat conversations, and this project already downloads and reads it.
    Sampling from it costs seconds and needs no generation at all.

    It is also the corpus the SAE's published feature exemplars index into
    (`seq_ids`/`positions` address rows of this same `tokens` array), so it is
    Gemma Scope's actual corpus rather than our reconstruction of its recipe
    from one sentence of their paper, and the text is byte-identical for anyone
    re-running -- no sampling temperature, no model-version drift.

    STATED LIMITATION: Google documents neither where this text came from nor
    whether the SAE was trained on it. If it was, the SAE's own reconstruction
    score here is in-sample and flattering to the SAE -- which makes the "NLA
    round trip beats the SAE" comparison HARDER to win, not easier, so the
    direction is safe. See METHODOLOGY.

    Works on token IDs throughout rather than decoding to text and re-applying
    the chat template: these are the exact tokens the SAE saw, and a
    detokenize/retokenize round trip is not guaranteed to reproduce them.
    """
    from huggingface_hub import hf_hub_download
    from safetensors import safe_open

    # Derived from the live tokenizer, never hardcoded -- the same rule the rest
    # of this project follows for token IDs (see CLAUDE.md, "sidecar is the
    # contract"). A tokenizer change would otherwise silently mis-split turns.
    sot = tok.convert_tokens_to_ids("<start_of_turn>")
    eot = tok.convert_tokens_to_ids("<end_of_turn>")
    uid = tok.encode("user", add_special_tokens=False)[0]
    mid = tok.encode("model", add_special_tokens=False)[0]
    nl = tok.encode("\n", add_special_tokens=False)[0]
    pad = tok.pad_token_id if tok.pad_token_id is not None else 0
    for nm, v in (("<start_of_turn>", sot), ("<end_of_turn>", eot)):
        assert v is not None and v >= 0, f"{nm} not in this tokenizer's vocab"

    path = hf_hub_download(_SAE_REPO, _SAE_EXAMPLES)
    out, seen, scanned = [], set(), 0
    with safe_open(path, framework="np") as f:
        sl = f.get_slice("tokens")
        total = sl.get_shape()[0]
        print(f"[data] SAE corpus has {total:,} conversations; sampling {n}")
        # Permutation, not repeated draws: guarantees distinct rows, and the
        # seed makes the selection reproducible.
        for i in np.random.default_rng(seed).permutation(total):
            if len(out) >= n:
                break
            scanned += 1
            ids = np.asarray(sl[int(i):int(i) + 1])[0]
            ids = ids[ids != pad]
            turns = [j for j in range(len(ids) - 1) if ids[j] == sot]
            u = next((j for j in turns if ids[j + 1] == uid), None)
            m = next((j for j in turns if ids[j + 1] == mid), None)
            if u is None or m is None or m <= u:
                continue
            us = u + 3 if ids[u + 2] == nl else u + 2        # past "<sot>user\n"
            ms = m + 3 if ids[m + 2] == nl else m + 2        # past "<sot>model\n"
            ue = next((j for j in range(us, m) if ids[j] == eot), m)
            # Enough response tokens to sample from AFTER _MIN_OFFSET is applied
            # inside the response -- the default leaves at least 16 candidate
            # positions, so this tracks _MIN_OFFSET rather than being a second
            # constant that can drift away from it.
            if len(ids) - ms < min_response_tokens:
                continue
            key = ids.tobytes()
            if key in seen:            # belt and braces; the corpus had none
                continue
            seen.add(key)
            out.append({
                "ids": ids.astype(np.int64),
                "n_prefix": int(ms),
                "prompt": tok.decode(ids[us:ue].tolist()),
                "response": tok.decode(ids[ms:].tolist()),
                "doc_id": f"saecorpus:{int(i)}",
            })
    if len(out) < n:
        raise SystemExit(f"only {len(out)} usable conversations of {n} wanted "
                         f"after scanning {scanned}")
    print(f"[data] kept {len(out)} (scanned {scanned}, rejected "
          f"{scanned - len(out)} for no model turn or a too-short response)")
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--arm", required=True,
                    choices=["saecorpus", "rollout", "wildchat"])
    ap.add_argument("--n-docs", type=int, default=10,
                    help="conversations to generate. ONE ACTIVATION EACH by "
                         "default, so this is also the number of independent "
                         "samples the experiment ends up with")
    ap.add_argument("--positions-per-doc", type=int, default=1,
                    help="activations taken from each conversation. LEAVE AT 1. "
                         "Two positions in one Gemma response share nearly all "
                         "their context -- an earlier run sampled 10 apiece and "
                         "two of them landed one token apart, which is not two "
                         "measurements of anything. Raising this inflates the "
                         "row count without adding independent samples, and "
                         "every downstream confidence interval silently narrows")
    ap.add_argument("--layer-index", type=int, default=32)
    ap.add_argument("--max-new-tokens", type=int, default=400, help="rollout arm only")
    ap.add_argument("--min-response-chars", type=int, default=400,
                    help="reject short Gemma responses. Without this, some prompts "
                         "elicit ~100-char replies, leaving too few response positions "
                         "to sample from -- the 10 sampled positions then come from one "
                         "short reply and are near-duplicates. Same bar the wildchat arm "
                         "applies to its assistant turns, so the two arms match.")
    ap.add_argument("--oversample", type=int, default=3,
                    help="generate this many times --n-docs prompts, since short "
                         "responses get rejected")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    sys.stdout.reconfigure(line_buffering=True)
    print("=" * 72); print(f"CHAT ACTIVATION EXTRACTION — arm={a.arm}"); print("=" * 72)

    tok = AutoTokenizer.from_pretrained(BASE)
    model = AutoModelForCausalLM.from_pretrained(BASE, dtype=torch.bfloat16).to(a.device)
    model = resolve_text_model(model); model.eval()

    # ---- build conversations ----
    # Every arm produces the same thing: a list of items carrying the token ids,
    # the index where the assistant response starts, and the text for the
    # parquet. Only the saecorpus arm skips generation.
    items: list[dict] = []
    if a.arm == "saecorpus":
        items = saecorpus_docs(a.n_docs, a.seed, tok)
    elif a.arm == "rollout":
        want = a.n_docs * a.oversample
        half = (want + 1) // 2
        prompts = quality_prompts_oasst(half, a.seed) + quality_prompts_lmsys(want - half, a.seed)
        print(f"[data] {len(prompts)} quality-filtered prompts "
              f"(oasst1 + LMSYS, as the Gemma Scope 2 paper specifies)")
        convs, srcs, rejected = [], [], 0
        for p in prompts:
            if len(convs) >= a.n_docs:
                break
            ids = tok.apply_chat_template([{"role": "user", "content": p}],
                                          tokenize=True, add_generation_prompt=True,
                                          return_tensors="pt").to(a.device)
            # SEEDED. Without this the rollout responses are unreproducible, and
            # when the parquet is lost the source text behind the results is gone
            # permanently -- which is exactly what happened to the first run.
            torch.manual_seed(a.seed * 100003 + len(convs))
            with torch.no_grad():
                g = model.generate(input_ids=ids, max_new_tokens=a.max_new_tokens,
                                   do_sample=True, temperature=1.0)
            resp = tok.decode(g[0][ids.shape[1]:], skip_special_tokens=True).strip()
            if len(resp) < a.min_response_chars:
                rejected += 1
                print(f"  [reject] prompt {len(p)}c -> response only {len(resp)}c")
                continue
            k = len(convs)
            convs.append([{"role": "user", "content": p},
                          {"role": "assistant", "content": resp}])
            srcs.append(f"rollout:oasst1+lmsys:{k}")
            print(f"  [{k}] prompt {len(p)}c -> Gemma response {len(resp)}c")
        print(f"[gen] kept {len(convs)}, rejected {rejected} for short responses")
        assert len(convs) >= a.n_docs, (
            f"only {len(convs)} usable of {a.n_docs} wanted -- raise --oversample")
    else:
        convs = wildchat_conversations(a.n_docs, a.seed)
        srcs = [f"wildchat:{k}" for k in range(len(convs))]
        print(f"[data] {len(convs)} quality-filtered WildChat conversations "
              f"(English, non-toxic, non-redacted, substantive assistant turn)")

    if a.arm != "saecorpus":
        # Apply the chat template and locate the response, as before. The prefix
        # runs through the user turn plus the generation header; everything
        # after it is the assistant response, which is the region both the SAE
        # and the NLA would have seen tokens from.
        for k, conv in enumerate(convs):
            full = tok.apply_chat_template(conv, tokenize=False)
            prefix = tok.apply_chat_template([conv[0]], tokenize=False,
                                             add_generation_prompt=True)
            ids = tok(full, return_tensors="pt", add_special_tokens=False).input_ids[0]
            n_prefix = tok(prefix, return_tensors="pt",
                           add_special_tokens=False).input_ids.shape[1]
            items.append({"ids": ids.numpy(), "n_prefix": int(n_prefix),
                          "prompt": conv[0]["content"],
                          "response": conv[1]["content"], "doc_id": srcs[k]})

    # ---- extract activations from inside the ASSISTANT RESPONSE ----
    special = set(tok.all_special_ids)          # paper masks pad/BOS/EOS
    rows, rng = [], np.random.default_rng(a.seed)
    for k, it in enumerate(items):
        ids = torch.as_tensor(it["ids"], dtype=torch.long, device=a.device)[None]
        n_prefix = it["n_prefix"]
        with torch.no_grad():
            hs = model(ids, output_hidden_states=True).hidden_states
        H = hs[a.layer_index + 1][0]            # --layer-index L == hidden_states[L+1]

        lo, hi = n_prefix + _MIN_OFFSET, ids.shape[1]
        cand = [p for p in range(lo, hi) if int(ids[0, p]) not in special]
        if len(cand) < a.positions_per_doc:
            print(f"  [skip] doc {k}: only {len(cand)} valid response positions")
            continue
        candset = set(cand)
        for p in rng.choice(cand, a.positions_per_doc, replace=False):
            # NEAR-MISS NEIGHBOURS, for the distance sweep in roundtrip.py.
            # The existing latent-overlap null compares against an UNRELATED
            # conversation, which is an easy null: two random activations share
            # almost nothing. The harder question is whether the match is
            # specific to THIS TOKEN or would hold anywhere nearby in the same
            # response -- same topic, same document, same speaker.
            #
            # Taken from the forward pass that is already running here. Doing it
            # later would mean loading Gemma a second time alongside the AV/AR,
            # which does not fit. No extra AV or AR work: the round trip still
            # happens only at p.
            #
            # Offsets that fall outside the valid region are DROPPED, not
            # clamped -- clamping would silently turn a +50 into a +30 and make
            # the curve's x-axis a lie. Which offsets survived is recorded per
            # row so attrition is visible downstream.
            nb_off, nb_vec = [], []
            for d in _NEIGHBOR_OFFSETS:
                q = int(p) + d
                if q in candset:          # in-response, past _MIN_OFFSET, not special
                    nb_off.append(d)
                    nb_vec.append(H[q].float().cpu().numpy().tolist())
            rows.append({
                "n_raw_tokens": int(ids.shape[1]),
                # Context the activation actually encodes: everything up to and
                # including its token. Capped, because it is what gets shown.
                "detokenized_text_truncated": tok.decode(ids[0, :int(p) + 1],
                                                          skip_special_tokens=True)[-2000:],
                # THE WHOLE CONVERSATION, UNCUT. The line above stops at the
                # activation and keeps only its last 2000 characters, so on its
                # own it loses the prompt and everything Gemma wrote afterwards.
                # Storing the full text costs a few MB across the corpus and is
                # the difference between being able to re-examine a case later
                # and not. An earlier corpus was generated unseeded and then
                # lost, and its text was unrecoverable.
                "prompt": it["prompt"],
                "response": it["response"],
                "activation_token_index": int(p),
                "response_start_index": int(n_prefix),
                "activation_vector": H[int(p)].float().cpu().numpy().tolist(),
                "activation_layer": a.layer_index,
                "doc_id": it["doc_id"],
                # Same conversation, same forward pass, offset by these many
                # tokens. Variable length: an offset that left the valid region
                # is absent rather than clamped.
                "neighbor_offsets": nb_off,
                "neighbor_vectors": nb_vec,
            })
        print(f"  doc {k}: {ids.shape[1]} tok, response starts at {n_prefix}, "
              f"{len(cand)} valid positions -> {a.positions_per_doc} sampled")

    t = pa.Table.from_pylist(rows)
    pq.write_table(t, a.out)
    Path(a.out + ".nla_meta.yaml").write_text(yaml.safe_dump({
        "kind": "nla_dataset", "schema_version": 1, "stage": "base",
        "row_count": len(rows),
        "dataset_id": f"chat_{a.arm}_gemma-3-12b-it_L{a.layer_index}",
        "extraction": {"base_model": BASE, "d_model": len(rows[0]["activation_vector"]),
                        "layer_index": a.layer_index, "norm": "none",
                        "corpus": {
                            "saecorpus": f"{_SAE_REPO}/{_SAE_EXAMPLES} `tokens` "
                                          "(the corpus Gemma Scope ships with the SAE)",
                            "rollout": "oasst1+lmsys prompts, Gemma-generated responses",
                            "wildchat": "allenai/WildChat-1M as-is",
                        }[a.arm],
                        "positions_per_doc": a.positions_per_doc,
                        "sampled_region": "assistant response only, special tokens masked"},
    }, sort_keys=False))
    print(f"\nwrote {len(rows)} rows from {len(set(r['doc_id'] for r in rows))} docs -> {a.out}")


if __name__ == "__main__":
    main()
